FROM php:7.3-fpm

LABEL maintainer="Jefferson Ramos"

# Set working directory
WORKDIR /var/www

# Install dependencies
RUN apt-get update && apt-get install -y \
    build-essential curl libpq-dev libfreetype6-dev libjpeg62-turbo-dev openssl libxml2-dev unzip libzip-dev \
    && docker-php-ext-install -j$(nproc) json xml pdo zip pdo_pgsql mbstring tokenizer ctype bcmath \
    && curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer \
    && apt-get clean

# Add user for laravel application
RUN groupadd -g 1000 www
RUN useradd -u 1000 -ms /bin/bash -g www www

# Copy existing application directory contents
COPY . /var/www

# Copy existing application directory permissions
COPY --chown=www:www . /var/www

# Change current user to www
USER www

# Expose port 9000 and start php-fpm server
EXPOSE 9000
CMD ["php-fpm"]
